### ISSUE TITLE
Solve a problem on codeforces & make PR

### ISSUE THREAD

**Issue by sagarmittal1** [sagarmittal1/test-repo#1]
In this issue you have to solve a problem in codeforces & then put the code in `code`  folder with appropriate naming (See the other example from reference)

Keep in mind the following
- Make a separate branch for it & push & make PR from the same.
- Make PR subject & body easy to understand & to the point

Good Luck

**Comment by Arpitgupta1014** [comment]
Hey @sagarmittal1 , can I solve your issue regarding codeforces. I will surely follow all the instructions given by your side.
Looking forward to working with you on this issue.
Thank you

**Comment by sagarmittal1** [comment]
@Arpitgupta1014 Great that's wonderful just put the link of the question you are going to solve & then start working on this issue
